package_rename_config:
  android:
    app_name: Auto Flashcards
    package_name: com.autoFlashcards.app
#    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
#    lang: # (Optional) (String) The android development language {kotlin(default) or java}
    bundle_name: com.auto_flashcards.app

  ios:
    app_name: Auto Flashcards
    bundle_name: com.autoFlashcards.app
    package_name: com.autoFlashcards.app

#  linux:
#    app_name: Auto Flashcards
#    package_name: # (String) The application id of the linux app
#    exe_name: # (String) The executable name (binary name) of the linux app

  macos:
    app_name: Auto Flashcards
    package_name: com.autoFlashcards.app
    copyright_notice: # (String) The product copyright of the macos app

  web:
    app_name: Auto Flashcards
    description: # (String) The description of the web app and PWA

#  windows:
#    app_name: # (String) The window title & software name of the windows app
#    organization: # (String) The organization name (company name) of the windows app
#    copyright_notice: # (String) The legal copyright of the windows app
#    exe_name: # (String) The executable name (binary name) of the windows app
